[build]
  publish = "dist"
  command = "pnpm run build"
  functions = "netlify/functions"

## used for Digital Asset Links File on Play store
[[redirects]]
  from = "/.well-known/*"
  to = "/well-known/:splat"
  status = 200

# register the correct MIME type for the web manifest
[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"

# files in /assets/ can have a very long cache time, as everything in there should contain a hash in the filename
[[headers]]
  for = "/assets/*"
  [headers.values]
    cache-control = '''
    max-age=31536000,
    immutable
    '''